/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.3/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

import org.gradle.api.tasks.testing.logging.TestLogEvent.*
import javax.inject.Inject
import org.gradle.process.ExecOperations

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    kotlin("jvm") version "2.0.21"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // No external dependencies needed for Advent of Code
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use Kotlin Test test framework
            useKotlinTest("2.1.20")
        }
    }
}

// Copy input.txt and README.md files from kotlin source to resources
sourceSets {
    main {
        resources {
            srcDir("src/main/kotlin")
            include("**/input.txt", "**/README.md")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "day01.Day01Kt"
}

// Custom task to run a specific day's solution
abstract class SolveTask : DefaultTask() {
    @get:Inject
    abstract val execOperations: ExecOperations
    
    @get:Input
    @get:Optional
    abstract val day: Property<String>
    
    @get:InputFiles
    abstract val runtimeClasspath: ConfigurableFileCollection
    
    @get:InputFile
    abstract val inputFile: RegularFileProperty
    
    @TaskAction
    fun solve() {
        val dayValue = if (day.isPresent) {
            day.get().padStart(2, '0')
        } else {
            throw GradleException("Please specify a day: gradle solve -Pday=1")
        }
        
        val solutionClass = "day${dayValue}.Day${dayValue}Kt"
        val inputFileLocation = inputFile.asFile.get()
        
        if (!inputFileLocation.exists()) {
            throw GradleException("Input file not found: ${inputFileLocation.absolutePath}")
        }
        
        println("🎄 Running Day $dayValue...")
        println("Input file: ${inputFileLocation.absolutePath}")
        
        // Execute the main class with input file
        execOperations.javaexec {
            classpath = runtimeClasspath
            mainClass.set(solutionClass)
            args = listOf(inputFileLocation.absolutePath)
        }
    }
}

tasks.register<SolveTask>("solve") {
    dependsOn("build")
    val dayValue = if (project.hasProperty("day")) {
        project.property("day").toString().padStart(2, '0')
    } else {
        "01" // default to day 1 for configuration
    }
    day.set(dayValue)
    runtimeClasspath.from(sourceSets["main"].runtimeClasspath)
    inputFile.set(layout.projectDirectory.file("src/main/kotlin/day$dayValue/input.txt"))
}
